############################# Server Basics #############################

process.roles=broker,controller
node.id=2
controller.quorum.bootstrap.servers=localhost:9093,localhost:9103,localhost:9113

############################# Socket Server Settings #############################

listeners=CLIENT://localhost:9102,CONTROLLER://localhost:9103
inter.broker.listener.name=CLIENT
advertised.listeners=CLIENT://localhost:9102
controller.listener.names=CONTROLLER
listener.security.protocol.map=CONTROLLER:PLAINTEXT,CLIENT:PLAINTEXT
num.network.threads=3
num.io.threads=8
socket.send.buffer.bytes=102400
socket.receive.buffer.bytes=102400
socket.request.max.bytes=104857600

############################# Log Basics #############################

log.dirs=/var/kafka/data/broker-2
num.partitions=3
num.recovery.threads.per.data.dir=1

############################# Internal Topic Settings #############################

offsets.topic.replication.factor=3
share.coordinator.state.topic.replication.factor=3
share.coordinator.state.topic.min.isr=2
transaction.state.log.replication.factor=3
transaction.state.log.min.isr=2

############################# Log Flush Policy #############################

#log.flush.interval.messages=10000
#log.flush.interval.ms=1000

############################# Log Retention Policy #############################

log.retention.hours=168
log.segment.bytes=1073741824
log.retention.check.interval.ms=300000
