package translator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Auto-provisioned authentication for the FTL SERVERS (the realm server and the pservers) -- as
// opposed to the Kafka listeners.
//
// Policy: if any Kafka listener is secured (cfg.IsSecure), the FTL servers must require
// authentication too. FSK does not support a secured Kafka listener running on FTL servers that
// accept unauthenticated connections. The FTL servers' authentication is their own login (FTL
// basic auth via a users file, and TLS later) and is independent of the Kafka listener security
// (PLAIN / OAuth / mTLS): the two only share the rule "if a Kafka listener is secured, the FTL
// servers authenticate too"; their user lists and protocols are otherwise separate.
//
// FTL permits authentication over an unencrypted connection, so a users file alone makes the FTL
// servers' pserver-to-pserver connections valid -- no certificates are needed to bring a secured
// cluster up. (FTL server TLS via auto-generated certificates is a later layer.)

// FTLInternal* is the login each tibftlserver presents to the other FTL servers (ftl-internal
// role); FTLAdmin* administers the realm REST (ftl-admin role). These log the FTL servers in --
// they are NOT the Kafka client users.
//
// Secret-scanner note (documented false positive, not a leak): the password literals below are
// PUBLISHED DEFAULT placeholders the tool writes into a throwaway cluster it generates from scratch.
// They protect only that just-created dev/test cluster -- nothing that pre-exists the run (cf. a
// sample shipping admin/admin). They must be plaintext because this is a basic-auth shared secret
// the tool both VERIFIES (the generated ftl-users.txt) and PRESENTS (the cluster YAML password
// field, see yaml.go), so hashing/encrypting the literal would be theater -- the cleartext still has
// to reach the wire. Real deployments override these with their own users file via --auth-users-file
// (see main.go), which takes precedence over this generated default.
const (
	FTLInternalUser     = "internal"
	FTLInternalPassword = "internal-pw"
	FTLAdminUser        = "admin"
	FTLAdminPassword    = "ftl-admin-pw"
)

// WriteFTLServerUsers writes the tool-generated FTL server users file (basic auth) into outputDir
// and returns its path. Format is the FTL users-file grammar: "user: password, role[,role...]".
func WriteFTLServerUsers(outputDir string) (string, error) {
	path := filepath.Join(outputDir, "ftl-users.txt")
	content := fmt.Sprintf(`# Tool-generated FTL SERVER users (basic auth) -- generated by tibftlimportconfig.
# These log the FTL servers in to each other and to the realm REST. They are SEPARATE from the
# Kafka listener credentials. Format: user: password, roles
%s: %s, ftl-internal
%s: %s, ftl-admin
all: all-pw, ftl-admin,ftl-internal
monitoring: monitoring-pw, ftl-monitoring
`, FTLInternalUser, FTLInternalPassword, FTLAdminUser, FTLAdminPassword)
	// 0600: the file embeds (placeholder) login credentials, so keep it readable only by the
	// owner that runs the tool and the FTL servers, not world-readable.
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return "", fmt.Errorf("write ftl-users.txt: %w", err)
	}
	return path, nil
}

// firstSetting returns the first present key's value, in precedence order.
func firstSetting(cfg *BrokerConfig, keys ...string) string {
	for _, k := range keys {
		if v, ok := cfg.Settings[k]; ok {
			return v
		}
	}
	return ""
}

// WriteKafkaClientUsers collects the inline SASL/PLAIN users (the JAAS
// user_<name>="<password>" entries) of every SASL listener across the broker
// configs and writes them to kafka-users.txt in the FTL users-file grammar
// (no roles). FSK validates SASL/PLAIN against the realm's shared
// auth.providers, and the raw sasl.jaas.config property is a Java construct
// (routed to unsupported.properties), so the inline user list must be
// materialized as a file: provider next to the FTL server users. Returns ""
// when no listener defines inline users. A user repeated across listeners or
// brokers must carry the same password.
func WriteKafkaClientUsers(outputDir string, cfgs []*BrokerConfig) (string, error) {
	users := map[string]string{}
	var order []string

	for _, cfg := range cfgs {
		for _, ld := range cfg.Listeners {
			// Only SASL listeners carry inline PLAIN users.
			if ld.Protocol != "SASL_PLAINTEXT" && ld.Protocol != "SASL_SSL" {
				continue // PLAINTEXT or SSL listener: no SASL handshake
			}
			if !strings.Contains(ld.SASLMech, "PLAIN") {
				continue // OAUTHBEARER-only listener: tokens, not passwords
			}
			// Kafka key precedence: per-listener-per-mechanism, then
			// per-listener, then global (the same forms jaasForHandlerKey
			// pairs elsewhere).
			lower := strings.ToLower(ld.Name)
			handler := firstSetting(cfg,
				"listener.name."+lower+".plain.sasl.server.callback.handler.class",
				"listener.name."+lower+".sasl.server.callback.handler.class",
				"sasl.server.callback.handler.class")
			jaas := firstSetting(cfg,
				"listener.name."+lower+".plain.sasl.jaas.config",
				"listener.name."+lower+".sasl.jaas.config",
				"sasl.jaas.config")
			a := resolveListenerAuth(jaas, handler)
			if a.Backend != BackendInline {
				continue
			}
			for i, u := range a.InlineUsers {
				pw := a.InlinePasswords[i]
				if prev, seen := users[u]; seen {
					if prev != pw {
						return "", fmt.Errorf("inline jaas user %q has conflicting passwords across listeners/brokers", u)
					}
					continue
				}
				users[u] = pw
				order = append(order, u)
			}
		}
	}

	if len(order) == 0 {
		return "", nil
	}

	var b strings.Builder
	b.WriteString(`# Tool-generated KAFKA CLIENT users -- generated by tibftlimportconfig from the
# inline JAAS user_<name> entries of the SASL/PLAIN listeners. FSK validates
# SASL/PLAIN against the realm auth.providers, so the inline users are
# delivered as a file: provider. Format: user: password
`)
	for _, u := range order {
		fmt.Fprintf(&b, "%s: %s\n", u, users[u])
	}

	path := filepath.Join(outputDir, "kafka-users.txt")
	if err := os.WriteFile(path, []byte(b.String()), 0o600); err != nil {
		return "", fmt.Errorf("write kafka-users.txt: %w", err)
	}
	return path, nil
}
