#!/usr/bin/env bash
#
# Copyright (c) 2026 Cloud Software Group, Inc.
# All Rights Reserved.
#
# Start 3 FSK pservers using configuration generated by tibftlimportconfig.
#
# Usage:
#   export TIBFTLSERVER=/opt/tibco/ftl/current-version/bin/tibftlserver   # or put it on PATH
#   bash demo/start-kof-brokers.sh [--output-dir ./kof-output]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KOF_OUTPUT_DIR="$SCRIPT_DIR/../kof-output"
LOG_DIR="/tmp/kof-brokers/logs"
PID_FILE="$SCRIPT_DIR/kof-brokers.pid"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output-dir) KOF_OUTPUT_DIR="$2"; shift 2 ;;
    *) echo "Unknown argument: $1"; exit 1 ;;
  esac
done

KOF_OUTPUT_DIR="$(cd "$KOF_OUTPUT_DIR" && pwd)"

# Resolve tibftlserver binary
if [[ -n "${TIBFTLSERVER:-}" ]]; then
  SERVER_BIN="$TIBFTLSERVER"
elif command -v tibftlserver &>/dev/null; then
  SERVER_BIN="tibftlserver"
elif [[ -n "${TIBFTLSERVER_HOME:-}" && -x "$TIBFTLSERVER_HOME/tibftlserver" ]]; then
  SERVER_BIN="$TIBFTLSERVER_HOME/tibftlserver"
else
  echo "ERROR: tibftlserver not found."
  echo "Set TIBFTLSERVER to the path of the tibftlserver binary, e.g.:"
  echo "  export TIBFTLSERVER=/opt/tibco/ftl/current-version/bin/tibftlserver"
  exit 1
fi

# The demo is a three-broker cluster, so tibftlimportconfig names the file
# tibftlserver-cluster.yaml. A single-broker conversion is named
# tibftlserver-standalone.yaml instead, and this script cannot use it: it starts
# SRV1/SRV2/SRV3, which a standalone output does not define.
CLUSTER_YAML="$KOF_OUTPUT_DIR/tibftlserver-cluster.yaml"
if [[ ! -f "$CLUSTER_YAML" ]]; then
  echo "ERROR: $CLUSTER_YAML not found."
  if [[ -f "$KOF_OUTPUT_DIR/tibftlserver-standalone.yaml" ]]; then
    echo "Found tibftlserver-standalone.yaml instead — that output came from a single broker."
    echo "This script starts SRV1/SRV2/SRV3; re-run tibftlimportconfig with all three"
    echo "demo/kraft/server-*.properties files."
  else
    echo "Run tibftlimportconfig against demo/kraft/server-*.properties first to generate kof-output/."
  fi
  exit 1
fi

# Stop any previously started pservers
if [[ -f "$PID_FILE" ]]; then
  echo "==> Stopping previously started FSK pservers"
  while IFS= read -r pid; do
    kill "$pid" 2>/dev/null && echo "  killed PID $pid" || true
  done < "$PID_FILE"
  rm -f "$PID_FILE"
  sleep 2
fi

mkdir -p "$LOG_DIR"
> "$PID_FILE"

echo "==> Starting FSK pservers from $CLUSTER_YAML"
for srv in SRV1 SRV2 SRV3; do
  log="$LOG_DIR/$srv.log"
  echo "  Starting $srv  (log: $log)"
  "$SERVER_BIN" -c "$CLUSTER_YAML" -n "$srv" > "$log" 2>&1 &
  echo "$!" >> "$PID_FILE"
done

echo ""
echo "✓ FSK pservers started (SRV1 / SRV2 / SRV3)."
echo "  PID file: $PID_FILE"
echo "  Logs:     $LOG_DIR/"
echo ""
echo "  Next: wait ~5 s for quorum, then run the migration:"
echo "    bash demo/run-migration.sh"
echo ""
echo "  To stop: bash demo/stop-kof-brokers.sh"
