/*
 * Copyright (c) 2026 Cloud Software Group, Inc.
 * All Rights Reserved.
 */

package translator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// WriteMigrationConfig generates a kafka-to-kof.properties file in outputDir.
// source.bootstrap.servers is populated from the advertised Kafka address of each
// input BrokerConfig (cfg.KOFHost:cfg.KOFPort).
// target.bootstrap.servers uses <KOF-HOST-N> placeholders with the same ports,
// since FSK pservers will run on different hosts but reuse the same Kafka listener port.
// Users replace the placeholders with actual pserver hostnames before running the migration.
func WriteMigrationConfig(cfgs []*BrokerConfig, outputDir string) error {
	path := filepath.Join(outputDir, "kafka-to-kof.properties")
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create %s: %w", path, err)
	}
	defer f.Close()

	src := make([]string, 0, len(cfgs))
	dst := make([]string, 0, len(cfgs))
	for i, cfg := range cfgs {
		// Prefer KafkaHost (pre-strip, includes inter-broker listeners that are
		// also client-capable). Fall back to KOFHost (post-strip client listener).
		host := cfg.KafkaHost
		port := cfg.KafkaPort
		if host == "" || host == "0.0.0.0" {
			host = cfg.KOFHost
			port = cfg.KOFPort
		}
		if host == "" || host == "0.0.0.0" {
			host = "localhost"
		}
		if port == 0 {
			port = 9092
		}
		src = append(src, fmt.Sprintf("%s:%d", host, port))
		dst = append(dst, fmt.Sprintf("<KOF-HOST-%d>:%d", i+1, port))
	}

	fmt.Fprintln(f, "# kafka-to-kof.properties — generated by tibftlimportconfig")
	fmt.Fprintln(f, "# Replace each <KOF-HOST-N> with the actual hostname of the corresponding FSK pserver.")
	fmt.Fprintln(f, "# Run in the directory holding run-apachekafka-to-fsk.sh:")
	fmt.Fprintln(f, "#   KAFKA_CLASSPATH=... ./run-apachekafka-to-fsk.sh --config <this-file> --dry-run")
	fmt.Fprintln(f, "#   KAFKA_CLASSPATH=... ./run-apachekafka-to-fsk.sh --config <this-file>")
	fmt.Fprintln(f)
	fmt.Fprintf(f, "source.bootstrap.servers=%s\n", strings.Join(src, ","))
	fmt.Fprintf(f, "target.bootstrap.servers=%s\n", strings.Join(dst, ","))
	fmt.Fprintln(f)
	fmt.Fprintln(f, "# Topic selection")
	fmt.Fprintln(f, "topic.pattern=.*")
	fmt.Fprintln(f, "include.internal=false")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "# Target topic settings")
	fmt.Fprintln(f, "target.replication.factor=1")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "# Runtime settings")
	fmt.Fprintln(f, "client.id=kafka-to-kof-replicator")
	fmt.Fprintln(f, "request.timeout.ms=60000")
	fmt.Fprintln(f, "max.empty.polls=15")
	fmt.Fprintln(f, "dry.run=false")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "# Records per batch per partition before flushing to FSK")
	fmt.Fprintln(f, "batch.size=1000")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "# Optional pass-through security (uncomment and fill in as needed)")
	fmt.Fprintln(f, "# source.admin.security.protocol=SASL_SSL")
	fmt.Fprintln(f, "# source.admin.sasl.mechanism=PLAIN")
	fmt.Fprintln(f, "# source.admin.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username=\"user\" password=\"pass\";")
	fmt.Fprintln(f, "# source.consumer.security.protocol=SASL_SSL")
	fmt.Fprintln(f, "# target.admin.security.protocol=SASL_SSL")
	fmt.Fprintln(f, "# target.producer.security.protocol=SASL_SSL")

	return nil
}
