package translator

import (
	"fmt"
	"os"
	"path/filepath"
)

// Auto-provisioned authentication for the FTL SERVERS (the realm server and the pservers) -- as
// opposed to the Kafka listeners.
//
// Policy: if any Kafka listener is secured (cfg.IsSecure), the FTL servers must require
// authentication too. KoF does not support a secured Kafka listener running on FTL servers that
// accept unauthenticated connections. The FTL servers' authentication is their own login (FTL
// basic auth via a users file, and TLS later) and is independent of the Kafka listener security
// (PLAIN / OAuth / mTLS): the two only share the rule "if a Kafka listener is secured, the FTL
// servers authenticate too"; their user lists and protocols are otherwise separate.
//
// FTL permits authentication over an unencrypted connection, so a users file alone makes the FTL
// servers' pserver-to-pserver connections valid -- no certificates are needed to bring a secured
// cluster up. (FTL server TLS via auto-generated certificates is a later layer.)

// FTLInternal* is the login each tibftlserver presents to the other FTL servers (ftl-internal
// role); FTLAdmin* administers the realm REST (ftl-admin role). These log the FTL servers in --
// they are NOT the Kafka client users.
//
// Secret-scanner note (documented false positive, not a leak): the password literals below are
// PUBLISHED DEFAULT placeholders the tool writes into a throwaway cluster it generates from scratch.
// They protect only that just-created dev/test cluster -- nothing that pre-exists the run (cf. a
// sample shipping admin/admin). They must be plaintext because this is a basic-auth shared secret
// the tool both VERIFIES (the generated ftl-users.txt) and PRESENTS (the cluster YAML password
// field, see yaml.go), so hashing/encrypting the literal would be theater -- the cleartext still has
// to reach the wire. Real deployments override these with their own users file via --auth-users-file
// (see main.go), which takes precedence over this generated default.
const (
	FTLInternalUser     = "internal"
	FTLInternalPassword = "internal-pw"
	FTLAdminUser        = "admin"
	FTLAdminPassword    = "ftl-admin-pw"
)

// WriteFTLServerUsers writes the tool-generated FTL server users file (basic auth) into outputDir
// and returns its path. Format is the FTL users-file grammar: "user: password, role[,role...]".
func WriteFTLServerUsers(outputDir string) (string, error) {
	path := filepath.Join(outputDir, "ftl-users.txt")
	content := fmt.Sprintf(`# Tool-generated FTL SERVER users (basic auth) -- generated by tibkafkatokof.
# These log the FTL servers in to each other and to the realm REST. They are SEPARATE from the
# Kafka listener credentials. Format: user: password, roles
%s: %s, ftl-internal
%s: %s, ftl-admin
all: all-pw, ftl-admin,ftl-internal
monitoring: monitoring-pw, ftl-monitoring
`, FTLInternalUser, FTLInternalPassword, FTLAdminUser, FTLAdminPassword)
	// 0600: the file embeds (placeholder) login credentials, so keep it readable only by the
	// owner that runs the tool and the FTL servers, not world-readable.
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return "", fmt.Errorf("write ftl-users.txt: %w", err)
	}
	return path, nil
}
