package translator

import (
	"fmt"
	"os"
	"path/filepath"
)

// listenerKeyOrder defines the listener-related keys emitted first.
var listenerKeyOrder = []string{
	"listeners",
	"advertised.listeners",
	"listener.security.protocol.map",
	"inter.broker.listener.name",
	"controller.listener.names",
}

// WriteKOFBrokerProperties writes kof.broker.properties as a flat Java-style
// key=value file mirroring the structure of the input server.properties.
func WriteKOFBrokerProperties(cfg *BrokerConfig, outputDir, _ string, _ int) error {
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}
	path := filepath.Join(outputDir, "kof.broker.properties")
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create kof.broker.properties: %w", err)
	}
	defer f.Close()
	writeKOFProps(f, cfg)
	fmt.Fprintf(os.Stdout, "wrote %s\n", path)
	return nil
}

func writeKOFProps(f *os.File, cfg *BrokerConfig) {
	fmt.Fprintf(f, "# KOF Broker Properties\n")
	fmt.Fprintf(f, "# Generated by tibkafkatokof from: %s\n", cfg.SourceFile)
	fmt.Fprintf(f, "# Node ID: %d\n", cfg.NodeID)
	fmt.Fprintln(f)

	// Emit standard listener keys first
	fmt.Fprintln(f, "# --- Listeners ---")
	emitted := make(map[string]bool)
	for _, k := range listenerKeyOrder {
		emitted[k] = true
		if v, ok := cfg.Settings[k]; ok {
			fmt.Fprintf(f, "%s=%s\n", k, v)
		}
	}
	// Emit per-listener.name.* keys (in insertion order)
	for _, k := range cfg.SettingKeys {
		if !emitted[k] && isListenerNameKey(k) {
			fmt.Fprintf(f, "%s=%s\n", k, cfg.Settings[k])
			emitted[k] = true
		}
	}
	fmt.Fprintln(f)

	// Emit all remaining properties in insertion order
	fmt.Fprintln(f, "# --- All remaining properties ---")
	for _, k := range cfg.SettingKeys {
		if !emitted[k] {
			fmt.Fprintf(f, "%s=%s\n", k, cfg.Settings[k])
		}
	}
}

func isListenerNameKey(k string) bool {
	const pfx = "listener.name."
	return len(k) > len(pfx) && k[:len(pfx)] == pfx
}
