package translator

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

// WriteRealmJSON generates realm.json with one kof.cluster per group of 3 pservers.
// transportType sets the transport_type field for all pserver connections ("auto" or "dtcp").
func WriteRealmJSON(cfg *BrokerConfig, outputDir, realmName string, numPservers int, drOpts DROpts, transportType string, copts ClusterOpts) error {
	path := filepath.Join(outputDir, "realm.json")
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create %s: %w", path, err)
	}
	defer f.Close()

	realm := buildRealm(cfg, realmName, numPservers, drOpts, transportType, copts)
	enc := json.NewEncoder(f)
	enc.SetIndent("", " ")
	return enc.Encode(realm)
}

func buildRealm(cfg *BrokerConfig, realmName string, numPservers int, drOpts DROpts, transportType string, copts ClusterOpts) map[string]any {
	name := realmName
	if name == "" {
		name = "_default_realm"
	}

	numClusters := (numPservers + 2) / 3
	if numClusters < 1 {
		numClusters = 1
	}
	clusters := make([]any, numClusters)
	for i := range clusters {
		clusters[i] = buildKOFCluster(cfg, i, numPservers, drOpts, transportType, copts)
	}

	return map[string]any{
		"name":                 name,
		"id":                   1,
		"version":              1,
		"realm_server_version": "7.3.0",
		"description":          "Generated by conversion tool",
		"product_data":         map[string]any{},
		"server_time":          "",
		"properties":           buildRealmProps(cfg, copts),
		"applications":         []any{},
		"clusters":             clusters,
		"connector_lists":     []any{},
		"destinations":        []any{},
		"eftl_clusters":        []any{},
		"external_transports":  []any{},
		"formats":              []any{},
		"transports":           []any{},
		"zones":                []any{},
	}
}

func buildRealmProps(cfg *BrokerConfig, copts ClusterOpts) map[string]any {
	return map[string]any{
		// Heartbeat / timeout
		"client_monitor_sample_interval": 60,
		"client_server_heartbeat":        60,
		"client_timeout_server":          180,
		"server_client_heartbeat":        60,
		"server_timeout_client":          3600,

		// Cluster defaults (from ftl-cluster.json reference)
		"cluster_disk_index_default_value":       !copts.DisableDiskIndex,
		"cluster_disk_persistence_default_value": "sync",
		"cluster_disk_swap_default_value":        true,

		// Client persistence / send policy defaults
		"com.tibco.ftl.client.map.persistence.retry.duration":        -1,
		"com.tibco.ftl.client.publisher.persistence.retry.duration":  -1,
		"com.tibco.ftl.client.publisher.persistence.send.policy":     0,
		"com.tibco.ftl.client.publisher.send.policy":                 1,
		"com.tibco.ftl.client.subscriber.nolocal.message.delivery":   false,
		"com.tibco.ftl.client.subscriber.persistence.retry.duration": -1,

		// Misc feature flags
		"compression_allowed":                    false,
		"enable_external_inbox_reply":             true,
		"enable_format_serialization_optimization": false,
		"enable_permissions":                     false,
		"manage_all_formats":                     false,
		"max_deployment_history":                 25,
		"monitor_matching_statistics":            false,
		"routable_default_cluster":               true,
		"service_connection_policy":              "default",
		"use_endpoint_store_for_inbox":           true,
		"user_friendly_name":                     "",

		// TLS / OpenSSL
		"openssl_cipher_suites":             "ECDHE-ECDSA-NULL-SHA:ECDHE-RSA-NULL-SHA",
		"openssl_cipher_suites_custom":      "",
		"openssl_cipher_suites_selection":   "defaults",
		"openssl_context_options":           "0x17134000",
		"openssl_context_options_custom":    "",
		"openssl_context_options_selection": "defaults",

		// Security
		"realm_is_secure":                cfg.IsSecure,
		"warn_about_insecure_transports": !cfg.IsSecure,
	}
}

// diskPersistenceModes maps a -disk-persistence flag token to the disk_persistence
// literal written into realm.json. "in-memory" is the realm model's NoDiskPersist,
// which is spelled as the empty string.
var diskPersistenceModes = map[string]string{
	"async":     "async",
	"sync":      "sync",
	"in-memory": "",
}

// DiskPersistenceModeNames lists the accepted -disk-persistence tokens, in help order.
var DiskPersistenceModeNames = []string{"async", "sync", "in-memory"}

// RealmDiskPersistence maps a -disk-persistence flag token to its realm.json literal,
// reporting false for an unrecognized token. The empty token selects the default,
// async, so a zero-valued ClusterOpts keeps the historical behavior.
func RealmDiskPersistence(mode string) (string, bool) {
	if mode == "" {
		return "async", true
	}
	literal, ok := diskPersistenceModes[mode]
	return literal, ok
}

// buildKOFCluster constructs the kof.cluster map per KOF requirements:
//   - cluster name: "kof.cluster.N" where N is the 0-based cluster index
//   - kof_enabled: true; disk_persistence from -disk-persistence (default async)
//   - 3 required stores: kof.data.store.N, kof.sync.store.N, kof.meta.store.N,
//     each overriding disk_persistence explicitly (see buildKOFStores)
//   - pserver_sets: one _setA set (non-DR) or _setA + _DRset (DR mode)
//
// In-memory turns off disk_index and disk_compact: the realm model rejects an index on
// disk without sync or async persistence ("indexes on disk requires sync or async disk
// persistence"), and compaction is inert with nothing on disk.
func buildKOFCluster(cfg *BrokerConfig, clusterIdx, numPservers int, drOpts DROpts, transportType string, copts ClusterOpts) map[string]any {
	startPserver := clusterIdx*3 + 1
	endPserver := min(startPserver+3, numPservers+1)
	clusterName := fmt.Sprintf("kof.cluster.%d", clusterIdx)

	// Validated in main before we get here; an unknown token falls back to the default.
	diskPersistence, _ := RealmDiskPersistence(copts.DiskPersistence)
	inMemory := diskPersistence == ""

	var pserverSets []any
	if drOpts.Enabled() {
		pserverSets = buildPserverSetsWithDR(clusterIdx, clusterName, startPserver, endPserver, cfg.IsSecure, transportType)
	} else {
		pserverSets = buildPserverSets(clusterIdx, clusterName, startPserver, endPserver, cfg.IsSecure, transportType)
	}

	return map[string]any{
		"acl": map[string]any{
			"roles": []any{},
			"users": []any{},
		},
		"bytelimit":                 "",
		"client_pserver_heartbeat":  2,
		"client_timeout_pserver":    5,
		"description":               "TIBCO FTL(R) Service for Kafka persistence cluster — generated by conversion tool",
		"disk_compact":              !inMemory,
		"disk_compact_settings":     map[string]any{"min_disk_inuse_ratio": 0.05},
		"disk_index":                !inMemory,
		"disk_persistence":          diskPersistence,
		"disk_swap":                 true,
		"dr_enabled":                drOpts.Enabled(),
		"force_quorum_delay":        0,
		"force_quorum_delay_factor": 10,
		"inter_cluster_heartbeat":   2,
		"inter_cluster_timeout":     5,
		"kof_enabled":               true,
		"last_modified":             "0001-01-01T00:00:00Z",
		"last_modified_by":          "",
		"last_modified_millis":      0,
		"message_limit":             0,
		"name":                      clusterName,
		"primary_set":               "_setA",
		"pserver_pserver_heartbeat": 0.5,
		"pserver_sets":              pserverSets,
		"pserver_timeout_pserver":   3,
		"stores":                    buildKOFStores(clusterIdx, inMemory),
	}
}

// buildPserverSets returns a single _setA pserver set containing pservers
// from startPserver (inclusive) to endPserver (exclusive).
func buildPserverSets(clusterIdx int, clusterName string, startPserver, endPserver int, isSecure bool, transportType string) []any {
	pservers := make([]any, endPserver-startPserver)
	for i := 0; i < endPserver-startPserver; i++ {
		pservers[i] = buildPserver(clusterIdx, clusterName, startPserver+i, isSecure, transportType)
	}
	return []any{map[string]any{
		"description":  "",
		"name":         "_setA",
		"pservers":     pservers,
		"reachability": map[string]any{},
		"role":         "persist",
	}}
}

// buildPserverSetsWithDR returns two pserver sets (_setA primary + _DRset DR replicas).
// In DR mode: dr_transport is populated; inter_cluster_transport is empty (roles swap vs. non-DR).
func buildPserverSetsWithDR(clusterIdx int, clusterName string, startPserver, endPserver int, isSecure bool, transportType string) []any {
	count := endPserver - startPserver
	primary := make([]any, count)
	dr := make([]any, count)
	for i := 0; i < count; i++ {
		pnum := startPserver + i
		primary[i] = buildPserverDRMode(clusterIdx, clusterName, pnum, isSecure, transportType)
		dr[i] = buildDRPserver(clusterIdx, clusterName, pnum, isSecure, transportType)
	}
	return []any{
		map[string]any{
			"description":  "",
			"name":         "_setA",
			"pservers":     primary,
			"reachability": map[string]any{},
			"role":         "persist",
		},
		map[string]any{
			"description":  "",
			"name":         "_DRset",
			"pservers":     dr,
			"reachability": map[string]any{},
			"role":         "persist",
		},
	}
}

// buildPserverDRMode builds a primary pserver in DR mode:
// dr_transport is populated; inter_cluster_transport is empty.
func buildPserverDRMode(clusterIdx int, clusterName string, pserverNum int, isSecure bool, transportType string) map[string]any {
	pserverName := fmt.Sprintf("pserver%d", pserverNum)
	prefix := fmt.Sprintf("kof_cluster_%d_pserver%d", clusterIdx, pserverNum)
	drTransportName := fmt.Sprintf("_disaster_recovery_transport_kof_cluster_%d_pserver%d", clusterIdx, pserverNum)

	return map[string]any{
		"name":                    pserverName,
		"weight":                  10,
		"description":             "",
		"last_modified":           "0001-01-01T00:00:00Z",
		"last_modified_by":        "",
		"last_modified_millis":    0,
		"dr_transport":            buildPserverTransport(drTransportName, "DR transport for "+clusterName, isSecure, transportType),
		"cluster_transport":       buildPserverTransport("_cluster_transport_"+prefix, "cluster transport for "+clusterName, isSecure, transportType),
		"inter_cluster_transport": map[string]any{},
		"client_transports": []any{map[string]any{
			"matchers":  []any{},
			"transport": buildTransportDef("_client_pri_transport_"+prefix, "client primary transport for "+clusterName, isSecure, transportType),
		}},
	}
}

// buildDRPserver builds a DR replica pserver entry.
// Named drpserverN; dr_transport populated; inter_cluster_transport empty.
func buildDRPserver(clusterIdx int, clusterName string, pserverNum int, isSecure bool, transportType string) map[string]any {
	pserverName := fmt.Sprintf("drpserver%d", pserverNum)
	prefix := fmt.Sprintf("kof_cluster_%d_drpserver%d", clusterIdx, pserverNum)
	drTransportName := fmt.Sprintf("_disaster_recovery_transport_kof_cluster_%d_drpserver%d", clusterIdx, pserverNum)

	return map[string]any{
		"name":                    pserverName,
		"weight":                  10,
		"description":             "",
		"last_modified":           "0001-01-01T00:00:00Z",
		"last_modified_by":        "",
		"last_modified_millis":    0,
		"dr_transport":            buildPserverTransport(drTransportName, "DR transport for "+clusterName, isSecure, transportType),
		"cluster_transport":       buildPserverTransport("_cluster_transport_"+prefix, "cluster transport for "+clusterName, isSecure, transportType),
		"inter_cluster_transport": map[string]any{},
		"client_transports": []any{map[string]any{
			"matchers":  []any{},
			"transport": buildTransportDef("_client_pri_transport_"+prefix, "client primary transport for "+clusterName, isSecure, transportType),
		}},
	}
}

// buildPserver builds one pserver entry following the ftl-cluster.json model.
// Transport names embed cluster index and pserver number for global uniqueness.
func buildPserver(clusterIdx int, clusterName string, pserverNum int, isSecure bool, transportType string) map[string]any {
	pserverName := fmt.Sprintf("pserver%d", pserverNum)
	// Dot-free prefix ensures unique transport names across the realm.
	prefix := fmt.Sprintf("kof_cluster_%d_pserver%d", clusterIdx, pserverNum)

	return map[string]any{
		"name":                 pserverName,
		"weight":               10,
		"description":          "",
		"last_modified":        "0001-01-01T00:00:00Z",
		"last_modified_by":     "",
		"last_modified_millis": 0,
		"dr_transport":         map[string]any{},
		"cluster_transport": buildPserverTransport(
			"_cluster_transport_"+prefix,
			"cluster transport for "+clusterName,
			isSecure,
			transportType,
		),
		"inter_cluster_transport": buildPserverTransport(
			"_inter_cluster_transport_"+prefix,
			"inter cluster transport for "+clusterName,
			isSecure,
			transportType,
		),
		"client_transports": []any{map[string]any{
			"matchers": []any{},
			"transport": buildTransportDef(
				"_client_pri_transport_"+prefix,
				"client primary transport for "+clusterName,
				isSecure,
				transportType,
			),
		}},
	}
}

func buildPserverTransport(name, desc string, isSecure bool, transportType string) map[string]any {
	return map[string]any{"transport": buildTransportDef(name, desc, isSecure, transportType)}
}

// buildTransportDef returns a transport definition matching the ftl-cluster.json reference:
// 256mb backlog; transportType sets transport_type ("auto" or "dtcp").
// isSecure adds "secure": true for encrypted realms.
func buildTransportDef(name, desc string, isSecure bool, transportType string) map[string]any {
	config := map[string]any{
		"backlog_full_wait": "0",
		"backlog_size":      "256mb",
		"recv_spin_limit":   "0",
		"transport_type":    transportType,
	}
	if isSecure {
		config["secure"] = true
	}
	return map[string]any{
		"config":               config,
		"description":          desc,
		"last_modified":        "0001-01-01T00:00:00Z",
		"last_modified_by":     "",
		"last_modified_millis": 0,
		"name":                 name,
		"relationships":        []any{},
	}
}

// buildKOFStores returns the three required KOF stores with their durable templates.
//
// Each store overrides the cluster's disk_persistence explicitly: the sync and meta
// stores are "sync" so their writes are durable, while the data store stays "async" for
// throughput on the bulk message path. Writing both out is the point of the override --
// the split then holds whichever of async or sync the cluster itself is set to.
//
// In-memory is the exception. An override of "sync" or "async" would send the stores to
// disk regardless, making -disk-persistence in-memory a no-op, so there the stores stay
// in-memory too: buildStore drops the key, and each store inherits the cluster.
func buildKOFStores(clusterIdx int, inMemory bool) []any {
	dataMode, durableMode := "async", "sync"
	if inMemory {
		dataMode, durableMode = "", ""
	}
	return []any{
		buildStore(fmt.Sprintf("kof.data.store.%d", clusterIdx), buildTemplate("kof.data.template", "shared"), dataMode),
		buildStore(fmt.Sprintf("kof.sync.store.%d", clusterIdx), buildTemplate("kof.sync.template", "shared"), durableMode),
		buildStore(fmt.Sprintf("kof.meta.store.%d", clusterIdx), buildTemplate("kof.meta.template", "lastvalue"), durableMode),
	}
}

// buildStore builds one store. An empty diskPersistence leaves the key out rather than
// writing "": StoreHeader.DiskPersistence is omitempty, so absent is how the model
// spells "inherit the cluster".
func buildStore(name string, template map[string]any, diskPersistence string) map[string]any {
	store := map[string]any{
		"acl": map[string]any{
			"roles": []any{},
			"users": []any{},
		},
		"bytelimit":             "",
		"description":           "",
		"durable_templates":     []any{template},
		"durables":              []any{},
		"dynamic_durable_limit": 0,
		"index":                 []any{},
		"last_modified":         "0001-01-01T00:00:00Z",
		"last_modified_by":      "",
		"last_modified_millis":  0,
		"max_message_size":      "",
		"message_limit":         0,
		"name":                  name,
		// publisher_settings.mode MUST be store_confirm_send per KOF requirements
		"publisher_settings": map[string]any{"mode": "store_confirm_send"},
		"replicated":         -1,
		"swap_bytelimit":     "",
		"zones":              []any{},
	}
	if diskPersistence != "" {
		store["disk_persistence"] = diskPersistence
	}
	return store
}

// buildTemplate builds a durable template per KOF requirements.
func buildTemplate(name, durableType string) map[string]any {
	return map[string]any{
		"ack_settings": map[string]any{
			"batch_count": 1000,
			"batch_time":  0.1,
			"mode":        "async",
		},
		"bytelimit":      "",
		"description":    "",
		"discard":        "old",
		"durable_ttl":    "0",
		"message_ttl":    "0",
		"name":           name,
		"prefetch":       1024,
		"retention_time": "0",
		"swap_bytelimit": "",
		"type":           durableType,
	}
}
