package translator

import (
	"fmt"
	"os"
	"path/filepath"
)

// SecureOpts holds the TLS and authentication values passed via CLI flags.
type SecureOpts struct {
	// TLS fields
	TLSCert        string
	TLSKey         string
	TLSKeyPassword string
	TLSCA          string

	// OAuth2 fields
	OAuthTokenURL      string
	OAuthJWKSURL       string
	OAuthClientID      string
	OAuthClientSecret  string
	OAuthProviderTrust string

	// Basic (file-based) auth
	AuthUsersFile string

	// mTLS — needed when a Kafka mTLS listener is present
	TLSServerTrust      string // tls.server.trust.file — CA used to verify inbound client certs
	TLSClientCert       string // tls.client.cert — cert presented when connecting to other FTL servers
	TLSClientKey        string // tls.client.private.key
	TLSClientKeyPassword string // tls.client.private.key.password (optional)
}

// ShouldWriteSecure reports whether a secure YAML should be generated.
// Requires security detected in the broker config AND at least one opt populated.
func ShouldWriteSecure(cfg *BrokerConfig, opts SecureOpts) bool {
	if !cfg.IsSecure {
		return false
	}
	return opts.TLSCert != "" || opts.OAuthTokenURL != "" || opts.AuthUsersFile != ""
}

// WriteKOFSecureYAML generates kof-cluster-secure.yaml for the primary cluster (first 3 pservers).
func WriteKOFSecureYAML(cfg *BrokerConfig, outputDir, dataDir, propsPath string, numPservers int, ports PortMap, coreServers []CoreServer, opts SecureOpts, drOpts DROpts) error {
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}
	path := filepath.Join(outputDir, "kof-cluster-secure.yaml")
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create %s: %w", path, err)
	}
	defer f.Close()

	host := resolveHost(cfg.KOFHost)
	cores := buildCoreServers(coreServers, host, ports)
	primaryCount := min3(numPservers)
	mode := secureMode(cfg, opts)

	fmt.Fprintln(f, "# KOF Cluster — Secure Configuration")
	fmt.Fprintf(f, "# Generated by tibkafkatokof from: %s\n", cfg.SourceFile)
	fmt.Fprintln(f, "#")
	fmt.Fprintf(f, "# Auth mode: %s\n", mode)
	fmt.Fprintln(f, "#")
	fmt.Fprintln(f, "# Start the cluster (one tibftlserver per SRV entry):")
	for i := 0; i < primaryCount; i++ {
		fmt.Fprintf(f, "#   tibftlserver --yaml kof-cluster-secure.yaml --server SRV%d\n", i+1)
	}
	fmt.Fprintln(f)

	fmt.Fprintln(f, "globals:")
	fmt.Fprintln(f, "  core.servers:")
	for _, c := range cores {
		fmt.Fprintf(f, "    %s: %s\n", c.Name, c.Address)
	}

	switch mode {
	case "oauth2":
		writeOAuthGlobals(f, opts)
	case "file-auth+tls":
		fmt.Fprintf(f, "  auth.providers: file:%s\n", opts.AuthUsersFile)
	}
	if drOpts.Enabled() {
		fmt.Fprintf(f, "  dr: %s\n", buildDRString(drOpts.DRServers))
		fmt.Fprintln(f, "  auto.init.primary.on.first.startup: true")
	}
	fmt.Fprintln(f)

	fmt.Fprintln(f, "servers:")
	for i := 0; i < primaryCount; i++ {
		fmt.Fprintf(f, "  SRV%d:\n", i+1)
		if drOpts.Enabled() {
			fmt.Fprintln(f, "  - realm:")
			fmt.Fprintln(f, "      label: PRIMARY_SERVER")
		} else {
			fmt.Fprintln(f, "  - realm: {}")
		}
		fmt.Fprintln(f, "  - ftlserver.properties:")
		if mode != "oauth2" {
			fmt.Fprintln(f, "      user: internal")
			fmt.Fprintln(f, "      password: internal-pw")
		}
		writeTLSProperties(f, opts)
		if mode == "oauth2" {
			writeOAuthServerProperties(f, opts)
		}
		fmt.Fprintln(f, "  - persistence:")
		fmt.Fprintf(f, "      name: pserver%d\n", i+1)
		fmt.Fprintf(f, "      data: %s/pserver%d\n", dataDir, i+1)
		fmt.Fprintf(f, "      kof.broker.properties: %s\n", propsPath)
		fmt.Fprintln(f, "      loglevel: connections:info;kof:info;durables:info;store:info")
		fmt.Fprintln(f)
	}

	fmt.Fprintln(f, "services:")
	fmt.Fprintln(f, "  persistence:")
	fmt.Fprintf(f, "    data: %s\n", dataDir)
	fmt.Fprintln(f, "  realm:")
	fmt.Fprintf(f, "    data: %s\n", dataDir)

	fmt.Fprintf(os.Stdout, "wrote %s\n", path)
	return nil
}

// secureMode returns "oauth2", "file-auth+tls", or "tls-only".
func secureMode(cfg *BrokerConfig, opts SecureOpts) string {
	for _, l := range cfg.Listeners {
		if l.AuthMethod == "oauth_tls" && opts.OAuthTokenURL != "" {
			return "oauth2"
		}
	}
	for _, l := range cfg.Listeners {
		if l.AuthMethod == "sasl_tls" && opts.AuthUsersFile != "" {
			return "file-auth+tls"
		}
	}
	return "tls-only"
}

func writeOAuthGlobals(f *os.File, opts SecureOpts) {
	fmt.Fprintln(f, "  auth.providers: oauth2")
	fmt.Fprintln(f, "  oauth2.claim.roles: group")
	fmt.Fprintln(f, "  oauth2.claim.username: preferred_username")
	fmt.Fprintln(f, "  oauth2.audience: ftl")
	if opts.OAuthTokenURL != "" {
		fmt.Fprintf(f, "  oauth2.svr.endpoint.token: %s\n", opts.OAuthTokenURL)
	}
}

func writeTLSProperties(f *os.File, opts SecureOpts) {
	if opts.TLSCert != "" {
		fmt.Fprintf(f, "      tls.server.cert: %s\n", opts.TLSCert)
	}
	if opts.TLSKey != "" {
		fmt.Fprintf(f, "      tls.server.private.key: %s\n", opts.TLSKey)
	}
	if opts.TLSKeyPassword != "" {
		fmt.Fprintf(f, "      tls.server.private.key.password: %s\n", opts.TLSKeyPassword)
	}
	if opts.TLSServerTrust != "" {
		fmt.Fprintf(f, "      tls.server.trust.file: %s\n", opts.TLSServerTrust)
	}
	if opts.TLSCA != "" {
		fmt.Fprintf(f, "      tls.client.trust.file: %s\n", opts.TLSCA)
	}
	if opts.TLSClientCert != "" {
		fmt.Fprintf(f, "      tls.client.cert: %s\n", opts.TLSClientCert)
	}
	if opts.TLSClientKey != "" {
		fmt.Fprintf(f, "      tls.client.private.key: %s\n", opts.TLSClientKey)
	}
	if opts.TLSClientKeyPassword != "" {
		fmt.Fprintf(f, "      tls.client.private.key.password: %s\n", opts.TLSClientKeyPassword)
	}
}

func writeOAuthServerProperties(f *os.File, opts SecureOpts) {
	if opts.OAuthJWKSURL != "" {
		fmt.Fprintf(f, "      oauth2.validation.key: %s\n", opts.OAuthJWKSURL)
	}
	if opts.OAuthProviderTrust != "" {
		fmt.Fprintf(f, "      oauth2.provider.trust.file: %s\n", opts.OAuthProviderTrust)
	}
	if opts.OAuthClientID != "" {
		fmt.Fprintf(f, "      oauth2.svr.client.id: %s\n", opts.OAuthClientID)
	}
	if opts.OAuthClientSecret != "" {
		fmt.Fprintf(f, "      oauth2.svr.client.secret: %s\n", opts.OAuthClientSecret)
	}
}
