#!/usr/bin/env bash
# Start 3 KOF pservers using configuration generated by tibkafkatokof.
#
# Usage:
#   export TIBFTLSERVER=/path/to/tibftlserver   # or put it on PATH
#   bash demo/start-kof-brokers.sh [--output-dir ./kof-output]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KOF_OUTPUT_DIR="$SCRIPT_DIR/../kof-output"
LOG_DIR="/tmp/kof-brokers/logs"
PID_FILE="$SCRIPT_DIR/kof-brokers.pid"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output-dir) KOF_OUTPUT_DIR="$2"; shift 2 ;;
    *) echo "Unknown argument: $1"; exit 1 ;;
  esac
done

KOF_OUTPUT_DIR="$(cd "$KOF_OUTPUT_DIR" && pwd)"

# Resolve tibftlserver binary
if [[ -n "${TIBFTLSERVER:-}" ]]; then
  SERVER_BIN="$TIBFTLSERVER"
elif command -v tibftlserver &>/dev/null; then
  SERVER_BIN="tibftlserver"
elif [[ -n "${TIBFTLSERVER_HOME:-}" && -x "$TIBFTLSERVER_HOME/tibftlserver" ]]; then
  SERVER_BIN="$TIBFTLSERVER_HOME/tibftlserver"
else
  echo "ERROR: tibftlserver not found."
  echo "Set TIBFTLSERVER to the path of the tibftlserver binary, e.g.:"
  echo "  export TIBFTLSERVER=/path/to/ftl/install/bin/tibftlserver"
  exit 1
fi

CLUSTER_YAML="$KOF_OUTPUT_DIR/kof-cluster.yaml"
if [[ ! -f "$CLUSTER_YAML" ]]; then
  echo "ERROR: $CLUSTER_YAML not found."
  echo "Run tibkafkatokof against demo/kraft/server-*.properties first to generate kof-output/."
  exit 1
fi

# Stop any previously started pservers
if [[ -f "$PID_FILE" ]]; then
  echo "==> Stopping previously started KOF pservers"
  while IFS= read -r pid; do
    kill "$pid" 2>/dev/null && echo "  killed PID $pid" || true
  done < "$PID_FILE"
  rm -f "$PID_FILE"
  sleep 2
fi

mkdir -p "$LOG_DIR"
> "$PID_FILE"

echo "==> Starting KOF pservers from $CLUSTER_YAML"
for srv in SRV1 SRV2 SRV3; do
  log="$LOG_DIR/$srv.log"
  echo "  Starting $srv  (log: $log)"
  "$SERVER_BIN" -c "$CLUSTER_YAML" -n "$srv" > "$log" 2>&1 &
  echo "$!" >> "$PID_FILE"
done

echo ""
echo "✓ KOF pservers started (SRV1 / SRV2 / SRV3)."
echo "  PID file: $PID_FILE"
echo "  Logs:     $LOG_DIR/"
echo ""
echo "  Next: wait ~5 s for quorum, then run the migration:"
echo "    bash demo/run-migration.sh"
echo ""
echo "  To stop: bash demo/stop-kof-brokers.sh"
